In [186]:
import sys
import os
import importlib

sys.path.insert(0, os.path.abspath('../..'))

import src.data_preprocessing as dp
importlib.reload(dp)

from src.data_preprocessing import *

In [187]:
df = load_dataset("../../data/raw/cardio_train.csv", sep=";")
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [188]:
df.duplicated().sum()

np.int64(0)

In [189]:
df = process_age(df, "age")
df = process_gender(df, "gender")
df = delete_columns(df, "id")
df.head()

,age,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,gender_male
0,50,168,62.0,110,80,1,1,0,0,1,0,0
1,55,156,85.0,140,90,3,1,0,0,1,1,1
2,51,165,64.0,130,70,3,1,0,0,0,1,1
3,48,169,82.0,150,100,1,1,0,0,1,1,0
4,47,156,56.0,100,60,1,1,0,0,0,0,1

In [190]:
df.isna().sum()

age            0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
gender_male    0
dtype: int64

In [191]:
df_clean = process_ap(df)

Nombre de lignes avant nettoyage : 70000
Nombre de lignes après nettoyage : 68672
Nombre de lignes supprimées : 1328
Pourcentage supprimé : 1.90%

In [192]:
df_clean = process_bmi(df_clean)

Nombre de lignes avant nettoyage : 68672
Nombre de lignes après nettoyage : 68606
Nombre de lignes supprimées : 66
Pourcentage supprimé : 0.10%

In [193]:
df_clean["BMI"].describe()

count    68606.000000
mean        27.448172
std          5.211817
min         10.726644
25%         23.875115
50%         26.346494
75%         30.116213
max         60.000000
Name: BMI, dtype: float64

In [194]:
save_dataset(df_clean, "../../data/processed/cardio_train.csv")