In [9]:
import sys
import os
import importlib
import src.data_preprocessing as dp

sys.path.insert(0, os.path.abspath('../..'))
importlib.reload(dp)

from src.data_preprocessing import *

In [10]:
df = load_dataset("../../data/raw/cardio_train.csv", sep=";")
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["age"] = df["age"].apply(process_age)
df["gender"] = df["gender"].map({1: "male", 2: "female"})
df = pd.get_dummies(df, columns=["gender"], drop_first=True, dtype=int)
df.drop(columns=["id"], inplace=True)
df.head()

,age,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,gender_male
0,50,168,62.0,110,80,1,1,0,0,1,0,0
1,55,156,85.0,140,90,3,1,0,0,1,1,1
2,51,165,64.0,130,70,3,1,0,0,0,1,1
3,48,169,82.0,150,100,1,1,0,0,1,1,0
4,47,156,56.0,100,60,1,1,0,0,0,0,1

In [13]:
df.isna().sum()

age            0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
gender_male    0
dtype: int64

In [32]:
save_dataset(df, "../../data/processed/cardio_train.csv")